#  Repositories : https://github.com/PaddlePaddle/PaddleOCR
#     Task type : OCR Text Detection
# Preprocessing : text_detection_label2ocr.py
#   Base config : configs/det/ch_PP-OCRv4/ch_PP-OCRv4_det_student.yml
#   Information : https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/PP-OCRv4_introduction.md
#                 https://github.com/PaddlePaddle/PaddleOCR/blob/main/doc/doc_ch/config.md

### Before training
#   1. replace ${task_name} and ${config_name}
#   2. set _dataset_root
#   3. set _batch_size
#   4. set _learning_rate

### Start training
#   python3 -m paddle.distributed.launch tools/train.py -c data/${task_name}/${config_name}.yml

### Visual prediction
#   python3 tools/infer_det.py -c data/${task_name}/${config_name}.yml -o Global.pretrained_model=workspace/${config_name}/best_accuracy Global.infer_img="data/test.jpg"

### Export inference model
#   python3 tools/export_model.py -c data/${task_name}/${config_name}.yml -o Global.pretrained_model=workspace/${config_name}/best_accuracy

########################################################################################
## dataset root
_dataset_root: &_dataset_root data/${task_name}/src
_label_path_train: &_label_path_train data/${task_name}/src/train.json
_label_path_test: &_label_path_test data/${task_name}/src/test.json

## train batch size
_batch_size: &_batch_size 16

## base learning rate
# new_lr = (default_base_lr * batch_size * num_gpus) / (default_batch_size * default_num_gpus)
# new_lr = (0.001 * batch_size * num_gpus) / (8 * 8)
_learning_rate: &_learning_rate 0.00025

#### >>>>> global <<<<< ######################################
Global:
  debug: false
  use_gpu: true
  epoch_num: &epoch_num 80
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: workspace/${config_name}
  save_epoch_step: 5
  eval_batch_step: [0, 384]
  cal_metric_during_train: false
  checkpoints: null
  pretrained_model: https://paddleocr.bj.bcebos.com/pretrained/PPLCNetV3_x0_75_ocr_det.pdparams
  save_inference_dir: workspace/${config_name}/inference
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./checkpoints/det_db/predicts_db.txt
  distributed: true

Architecture:
  model_type: det
  algorithm: DB
  Transform: null
  Backbone:
    name: PPLCNetV3
    scale: 0.75
    det: True
  Neck:
    name: RSEFPN
    out_channels: 96
    shortcut: True
  Head:
    name: DBHead
    k: 50

Loss:
  name: DBLoss
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: *_learning_rate
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 5.0e-05

PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5

Metric:
  name: DetMetric
  main_indicator: hmean

Train:
  dataset:
    name: SimpleDataSet
    data_dir: *_dataset_root
    label_file_list: *_label_path_train
    ratio_list: [1.0]
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - CopyPaste: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 640
        - 640
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
        total_epoch: *epoch_num
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
        total_epoch: *epoch_num
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: *_batch_size
    num_workers: 8

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: *_dataset_root
    label_file_list: *_label_path_test
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 8
profiler_options: null
