#  Repositories : https://github.com/PaddlePaddle/PaddleSeg
#     Task type : Common Semantic Segmentation
# Preprocessing : segmentation_labelme2seg.py
#   Base config : configs/pp_liteseg/pp_liteseg_stdc2_camvid_960x720_10k.yml
#   Information : https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.9/configs/pp_liteseg

### Before training
#   1. replace ${task_name} and ${config_name}
#   2. set _dataset_root
#   3. set _num_classes (including background)
#   4. set _batch_size
#   5. set _learning_rate

### Start training
#   python3 tools/train.py --config data/${task_name}/${config_name}.yml --do_eval

### Recovery after interruption (without suffix name '.pdparams', '.pdopt', '.pdema')
#   python3 tools/train.py --config data/${task_name}/${config_name}.yml --do_eval -r workspace/${config_name}/model

### Visual prediction
#   python3 tools/predict.py --config data/${task_name}/${config_name}.yml --model_path workspace/${task_name}/best_model/model.pdparams --image_path data/${task_name}/src/test.txt --save_dir workspace/${task_name}/predict

### Export inference model
#   python3 tools/export_model.py --config data/${task_name}/${config_name}.yml --input_shape 1 3 512 512 --model_path workspace/${task_name}/best_model/model.pdparams --save_dir workspace/${task_name}/inference

########################################################################################
## dataset root
_dataset_root: &_dataset_root data/${task_name}/src
_label_path_train: &_label_path_train data/${task_name}/src/train.txt
_label_path_test: &_label_path_test data/${task_name}/src/test.txt

## number of classes
_num_classes: &_num_classes 3

## train batch size
_batch_size: &_batch_size 16

## base learning rate
# new_lr = (default_base_lr * batch_size * num_gpus) / (default_batch_size * default_num_gpus)
# new_lr = (0.01 * batch_size * num_gpus) / (6 * 4)
_learning_rate: &_learning_rate 0.01

#### >>>>> global <<<<< ######################################
_base_: '../../configs/pp_liteseg/pp_liteseg_stdc2_camvid_960x720_10k.yml'

batch_size: *_batch_size

train_dataset:
  dataset_root: *_dataset_root
  num_classes: *_num_classes
  train_path: *_label_path_train
val_dataset:
  dataset_root: *_dataset_root
  num_classes: *_num_classes
  val_path: *_label_path_test

lr_scheduler:
  learning_rate: *_learning_rate

loss:
  types:
    - type: OhemCrossEntropyLoss
      min_kept: 250000   # batch_size * 960 * 720 // 16
    - type: OhemCrossEntropyLoss
      min_kept: 250000
    - type: OhemCrossEntropyLoss
      min_kept: 250000
  coef: [1, 1, 1]

model:
  _inherited_: False  # not inherit the model params from the base yaml
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
