#  Repositories : https://github.com/PaddlePaddle/PaddleDetection
#     Task type : Common Object Detection
# Preprocessing : object_detection_labelme2coco_segmentation.py
#   Base config : configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_dota.yml
#   Information : https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/configs/rotate/ppyoloe_r

### Before training
#   1. replace ${task_name} and ${config_name}
#   2. set _dataset_root
#   3. set _num_classes
#   4. set _batch_size
#   5. set _learning_rate

### Start training
#   python3 -m paddle.distributed.launch tools/train.py -c data/${task_name}/${config_name}.yml --eval --amp

### Recovery after interruption (without suffix name '.pdparams', '.pdopt', '.pdema')
#   python3 -m paddle.distributed.launch tools/train.py -c data/${task_name}/${config_name}.yml --eval --amp -r workspace/${config_name}/34

### Export inference model
#   python3 tools/export_model.py -c data/${task_name}/${config_name}.yml --output_dir workspace/${task_name} -o export_onnx=True

########################################################################################
## dataset root
_dataset_root: &_dataset_root data/${task_name}/src
_label_path_train: &_label_path_train train.json
_label_path_test: &_label_path_test test.json

## number of classes
_num_classes: &_num_classes 1

## train batch size (Use default batch_size to converge faster)
_batch_size: &_batch_size 2

## base learning rate
# new_lr = (default_base_lr * batch_size * num_gpus) / (default_batch_size * default_num_gpus)
# new_lr = (0.008 * batch_size * num_gpus) / (2 * 4)
_learning_rate: &_learning_rate 0.002

#### >>>>> global <<<<< ######################################
_BASE_: [
  '../../configs/runtime.yml',
  '../../configs/rotate/ppyoloe_r/_base_/optimizer_3x.yml',
  '../../configs/rotate/ppyoloe_r/_base_/ppyoloe_r_crn.yml',
  '../../configs/rotate/ppyoloe_r/_base_/ppyoloe_r_reader.yml',
]

### Base config : configs/rotate/ppyoloe_r/_base_/ppyoloe_r_reader.yml
# 训练第二步模型时需要手动在文件中修改 image_size: [512, 512]
worker_num: 8
TrainReader:
  batch_size: *_batch_size

### Base config : configs/rotate/ppyoloe_r/_base_/optimizer_3x.yml
LearningRate:
  base_lr: *_learning_rate

### Base config : configs/datasets/dota.yml
num_classes: *_num_classes
metric: RBOX
TrainDataset:
  name: COCODataSet
  image_dir: .
  anno_path: *_label_path_train
  dataset_dir: *_dataset_root
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
EvalDataset:
  name: COCODataSet
  image_dir: .
  anno_path: *_label_path_test
  dataset_dir: *_dataset_root
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd', 'gt_poly']
TestDataset:
  name: COCODataSet
  image_dir: .
  anno_path: *_label_path_test
  dataset_dir: *_dataset_root

### Base config : configs/rotate/ppyoloe_r/ppyoloe_r_crn_s_3x_dota.yml
log_iter: 20
snapshot_epoch: 3
weights: workspace/${task_name}/best_model.pdparams
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_s_pretrained.pdparams
depth_mult: 0.33
width_mult: 0.50

### Base config : configs/runtime.yml
save_dir: workspace/${task_name}
